#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit

readarray -t SOCIALS << "EOF"
GitHub|https://gboling.dev/github.html
LinkedIn|https://gboling.dev/linkedin.html
Instagram|https://gboling.dev/instagram.html
WhatsApp|https://gboling.dev/whatsapp.html
Telegram|https://gboling.dev/telegram.html
Messenger|https://gboling.dev/messenger.html
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
