#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
# 
# Modified by: Garrett Boling
# Date: February 05, 2026
# License: MIT

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Hello! My name is Garrett Boling.
I'm a fullstack developer and data scientist.
Connect with me on my socials or use this site
to easily browse my portfolio!
EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
