#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit

readarray -t SOCIALS << "EOF"
GitHub|https://github.com/garrett-boling
LinkedIn|https://www.linkedin.com/in/garrett-boling-04174b196/
Instagram|https://www.instagram.com/garrett.boling1212
WhatsApp|https://wa.me/18642079092
Telegram|https://t.me/gboling02
Messenger|https://m.me/garrett.boling1212
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
