#!/usr/bin/env bash
#
# Loop each episode and generate a tab-separated list of all episodes seen to
# stdout
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT
#
# Modified by: Garrett Boling
# Date: February 06, 2026
# License: MIT

dir=${1:-./projects}

for pt in "$dir"/pt*/meta.txt; do
	mapfile -t lines < "$pt"

	# read the meta at the top
	title=${lines[0]}
	num=${title%%.*}
	title=${title#*. }
	link=${lines[2]}
	desc=${lines[1]}
	start_index=3
	if [[ -z $link || $link == tiktok* || $link == youtube* || link == instagram* ]]; then
	  link=/v/$num
	  start_index=2
	fi

	# read the key values pairs at the bottom
	lines=("${lines[@]:$start_index}")
	declare -A links=()
	for line in "${lines[@]}"; do
		read -r key value <<< "$line"
		[[ -n $key && -n $value ]] || continue
		links[$key]=$value
	done

	tiktok=${links[tiktok]}
	youtube=${links[youtube]}
	instagram=${links[instagram]}

	printf '%s\t' "$num" "$title" "$desc" "$link" "$tiktok" "$youtube" "$instagram"
	echo
done
