#!/usr/bin/env bash
#
# Convert the list of episodes into JSON format - pass an argument to make it
# JSONP instead.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT
#
# Modified by: Garrett Boling
# Date: February 06, 2026
# License: MIT

varname=$1


# read data
objects=()
while IFS=$'\t' read -r num title desc link; do
	object=$(jq -nc \
		--arg title "$title" \
		--arg desc "$desc" \
		--arg link "$link" \
		--argjson num "$num" \
		'{
			"title": $title,
			"desc": $desc,
			"link": $link,
			"num": $num
		}'
	) || exit
	objects+=("$object")
done < <(./make-list)

# generate output JSON
printf -v now '%(%s)T' -1
output=$(printf '%s\n' "${objects[@]}" | jq -n \
    --argjson date "$now" \
    --arg link "$baselink" \
    '{
        "name": "Garrett Boling Projects",
        "site": $link,
        "generated": $date,
        "links": [inputs]
     }'
)

# print the data (optionally as jsonp if the first arg is set)
if [[ -n $varname ]]; then
	output="const $varname = $output;"
fi
echo "$output"
