#!/usr/bin/env bash
#
# My personal color theme for the website - loosely based on a dark solarized
# theme
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 28, 2025
# License: MIT

COLOR1=$'\x1b[38;5;87m'   # cyan
COLOR2=$'\x1b[38;5;211m'  # magenta
COLOR3=$'\x1b[38;5;120m'  # green
COLOR4=$'\x1b[38;5;241m'  # dim
COLOR5=$'\x1b[38;5;223m'  # off-white (text)

RST=$'\x1b[0m'

# vertical gradient: green → blue → purple
GRADIENT=(
  $'\e[38;5;46m'   # green
  $'\e[38;5;48m'
  $'\e[38;5;50m'
  $'\e[38;5;45m'   # cyan-ish
  $'\e[38;5;39m'   # blue
  $'\e[38;5;33m'
  $'\e[38;5;27m'
  $'\e[38;5;63m'   # blue-purple
  $'\e[38;5;93m'
  $'\e[38;5;129m'  # purple
  $'\e[38;5;165m'
  $'\e[38;5;201m'  # magenta-purple
)
